# Generated by Django 6.0.5 on 2026-06-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('BOA', 'Boarding'), ('DEP', 'Departed'), ('DEL', 'Senior'), ('CAN', 'Cancelled')], default='SCH', max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOO', 'Booked'), ('CAN', 'Cancelled'), ('USE', 'Used')], default='BOO', max_length=3)),
                ('seat', models.IntegerField()),
                ('trip', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('airplanes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('airlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('airports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.airport')),
            ],
        ),
        migrations.AddField(
            model_name='airplane',
            name='flights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.ticket'),
        ),
    ]
