# Generated by Django 6.0.5 on 2026-06-08 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seat',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='num_seats',
            new_name='num_seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airports.seat'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('num_seat', 'airplane'), name='unique_seat'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
