# Generated by Django 6.0.5 on 2026-06-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.AddField(
            model_name='airline',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='headquarters',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='num_seats',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(default='Unknown city', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='visa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='source',
            field=models.CharField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplane',
            name='flights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airports.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('SENIOR', 'Senior'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=9),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airports.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('USED', 'Used')], default='BOOKED', max_length=9),
        ),
    ]
