# Generated by Django 6.0.5 on 2026-06-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_seattype_airline_alter_airline_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seattype',
            name='airline',
        ),
        migrations.AddField(
            model_name='seattype',
            name='airplane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='airports.airplane'),
        ),
    ]
