# Generated by Django 6.0.5 on 2026-06-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_remove_seattype_airline_seattype_airplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seattype',
            name='airplane',
        ),
    ]
