# Generated by Django 6.0.5 on 2026-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_remove_seattype_airplane'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='num_seats',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
