# Generated by Django 6.0.5 on 2026-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0005_airplane_num_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='airplane',
            name='seat_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='airplanes', to='airports.seattype'),
        ),
    ]
