# Generated by Django 6.0.5 on 2026-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0006_remove_airplane_seat_type_airplane_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='num_seats',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seat_type',
            field=models.ManyToManyField(related_name='airplanes', to='airports.seattype'),
        ),
    ]
