# Generated by Django 6.0.5 on 2026-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0007_remove_airplane_num_seats_alter_airplane_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(max_length=5),
        ),
    ]
