# Generated by Django 6.0.5 on 2026-06-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0008_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
