# Generated by Django 6.0.5 on 2026-06-17 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0009_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Country code must be a two-letter uppercase code UA, US, FR', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
