# Generated by Django 6.0.5 on 2026-06-17 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0010_alter_country_code_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Airport code must be a three-letter uppercase code LAX, JFK, CDG', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
