# Generated by Django 6.0.5 on 2026-06-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0011_alter_airline_name_alter_airport_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
