# Generated by Django 6.0.5 on 2026-06-22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def normalize_seat_type_counts(apps, schema_editor):
    SeatType = apps.get_model("airports", "SeatType")
    for seat_type in SeatType.objects.all():
        changed = False
        for field_name in ("num_seats", "num_rows", "seats_in_row"):
            value = getattr(seat_type, field_name)
            if value is not None and value < 0:
                setattr(seat_type, field_name, abs(value))
                changed = True
        if changed:
            seat_type.save(update_fields=["num_seats", "num_rows", "seats_in_row"])


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0011_alter_airline_name_alter_airport_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="seat_type",
        ),
        migrations.AddField(
            model_name="seattype",
            name="airplane",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_type",
                to="airports.airplane",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(normalize_seat_type_counts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="airline",
            name="founded_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Founded year must be a four-digit year starting with 19 or 20.",
                        regex="^(19|20)\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airline",
            name="headquarters",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Headquarters must start with a capital letter and coniain only letters, spaces or hyphens.",
                        regex="^[A-Z][A-Za-z\\s\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airline",
            name="name",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Airline name must start with a capital letter and contain only letters, spaces or hyphens.",
                        regex="^[A-Z][A-Za-z\\s\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="model",
            field=models.CharField(
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Airplane models must start with a capital letter and contain only letters, numbers, spaces or hypenus",
                        regex="^[A-Z][A-Za-z0-9\\s\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="reg_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Registration number must start with the two capital letter and two numbers",
                        regex="^[A-Z]{2}\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="code",
            field=models.CharField(
                max_length=5,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Airport code must be a three-letter uppercase code LAX, JFK, CDG.",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="City name must start with a capital letter and contain only letters, spaces or hyphens.",
                        regex="^[A-Z][A-Za-z\\s\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Country code must be a two-letter uppercase code UA, US, FR.",
                        regex="^[A-Z]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                max_length=31,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Country name must start with a letter and contain only letters, spaces or hyphens.",
                        regex="^[A-Z][A-Za-z\\s\\-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="seattype",
            name="num_rows",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="seattype",
            name="num_seats",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="seattype",
            name="seats_in_row",
            field=models.PositiveIntegerField(),
        ),
    ]
