# Generated by Django 6.0.5 on 2026-06-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0012_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='seattype',
            name='airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='airports.airplane'),
            preserve_default=False,
        ),
    ]
