# Generated by Django 6.0.5 on 2026-06-25 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0012_update_airport_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='headquarters',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Headquarters must start with a capital letter and contain only letters, spaces or hyphens.', regex='^[A-Z][A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='model',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(message='Airplane models must start with a capital letter and contain only letters, numbers, spaces or hyphens', regex='^[A-Z][A-Za-z0-9\\s\\-]+$')]),
        ),
    ]
