# Generated by Django 6.0.5 on 2026-07-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0013_alter_airline_headquarters_alter_airplane_model'),
        ('airports', '0013_remove_airplane_seat_type_seattype_airplane'),
    ]

    operations = [
    ]
