# Generated by Django 6.0.5 on 2026-08-19 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0014_merge_20260701_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='Founded year must be 1900 or later.'), django.core.validators.MaxValueValidator(2099, message='Founded year must be 2099 or earlier.')]),
        ),
    ]
