# Generated by Django 6.0.5 on 2026-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0015_alter_airline_founded_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.PositiveIntegerField(default=0, help_text='Economy fare in cents. Other classes are derived from it.'),
        ),
    ]
