# Generated by Django 6.0.5 on 2026-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'user')], default='User', max_length=15),
        ),
    ]
