# Generated by Django 6.0.5 on 2026-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(default=200, help_text='Price in cents (e.g. 2000 = $20.00)'),
            preserve_default=False,
        ),
    ]
