# Generated by Django 6.0.7 on 2026-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
