# Generated by Django 6.0.5 on 2026-07-22 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0014_merge_20260701_1533'),
        ('tickets', '0005_order_booked_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['BOOKED', 'USED'])), fields=('seat', 'flight'), name='unique_active_ticket'),
        ),
    ]
